### ISSUE TITLE
Bug Report #3: 

### ISSUE THREAD

**Issue by Ulton321** [damianleng/hotel-booking-web-app#28]
### Description
After selecting a room and proceeding to the checkout, the checkout page begins loading but cannot be canceled, leaving the user stuck on the loading screen without an option to go back or cancel the process.

### Steps to Reproduce
1. Go to the room-select page.
2. Choose a room and click "Proceed to Checkout."
3. Observe that the checkout page starts loading.
4. Attempt to cancel the checkout process or navigate away.

### Expected Behavior
Upon proceeding to checkout:
- The checkout page should load completely, allowing the user to either complete the process or cancel it.
- If the user decides to cancel, there should be an option to return to the previous page or exit the checkout.

### Actual Behavior
- The checkout page remains in a loading state.
- There is no visible option to cancel the loading or return to the room selection page.

### Potential Cause
It seems that the frontend does not properly handle loading transitions for the checkout page. The logic for canceling or navigating away during the checkout process might be missing or incorrectly implemented.

### Suggested Fix
- Ensure that the loading state for the checkout page is correctly managed, with a timeout or loading indicator.
- Implement a cancel option during the checkout process, allowing users to navigate back to the room selection page or abort the current checkout.

**Comment by ThikaHok** [comment]
## **Solution**
- **Fix Implemented**: 
  The issue was resolved by **redirecting to `/home` instead of `/login`** during the checkout process. This ensures that the checkout loading issue is bypassed, preventing the user from being stuck on the loading page, and avoiding unnecessary form triggers.
